# Toeplitz matrix

Reference:

- AMP Chapter 7
- [Python companion](https://ses.library.usyd.edu.au/handle/2123/21370)

In [1]:
import numpy as np

## Convolution

The convolution of $n$-vector $a$ and $m$-vector $b$ is $(n + m -1)$-vector can be written as $c = a * b$

Each element of $c$ can be written as follows:

$$
c_k = \sum_{i + j = k + 1}a_i b_j, \quad k = 1, \cdots, n+m-1
$$

$$
c_1 = a_1b_1 , \quad
c_2 = a_1b_2 + a_2b_1 , \cdots
$$

For example, the convolution of $a$ and $b$ are:

$$
a = 
\begin{bmatrix}
1 \\ 0 \\ -1
\end{bmatrix}
\quad
b = 
\begin{bmatrix}
2 \\ 1 \\ -1
\end{bmatrix}
\quad
a * b = 
\begin{bmatrix}
2 \\ 1 \\ -3\\-1 \\1
\end{bmatrix}
$$

In [11]:
a = np.array([1, 0, -1])
print("vector a:")
a

vector a:


array([ 1,  0, -1])

In [12]:
b = np.array([2, 1, -1])
print("vector b:")
b

vector b:


array([ 2,  1, -1])

In [13]:
conv = np.convolve(a, b)
print("the convolution of a and b")
conv

the convolution of a and b


array([ 2,  1, -3, -1,  1])

## Toeplitz matrix

The convolution can be expressed as inner products using Toeplitz matrix:

$$
a * b = T(a)b = T(b)a, \quad
\text{where }
T(b) \text{ is the } (n + m - 1)\times n \ \text{matrix} 
$$

$$
T(b)_{ij} = \left\{
\begin{array}\\
b_{i-j+1} &1\leq i - j + 1 \leq m \\
0 & \text{otherwise}
\end{array}
\right.
$$


When $n = 3$ and $m = 3$, $T(b)$ is:

$$
T(b) = \begin{bmatrix}
b_1 & 0 & 0  \\
b_2 & b_1 & 0 \\
b_3 & b_2 & b_1 \\
0 & b_3 & b_2 \\
 0 & 0 & b_3 
\end{bmatrix} 
= 
\begin{bmatrix}
2 & 0 & 0  \\
1 & 2 & 0 \\
-1 & 1 & 2 \\
0 & -1 & 1 \\
 0 & 0 & -1 
\end{bmatrix} 
$$

In [16]:
# define function computing Toeplitz matrix
def toeplitz(b, n):
    # compute Toeplitz matrix T(b) for the convolution a * b
    
    # arguments:
    # b: original matrix. If T(b), b is original matrix
    # n: dimension of vector a

    m = len(b)
    T = np.zeros((n+m-1, n))
    for j in range(n):
        T[j:j+m, j] = bb
        
    return T

In [26]:
print("Toeplitz matrix for b:")
toeplitz(b, len(a))

Toeplitz matrix for b:


array([[ 2.,  0.,  0.],
       [ 1.,  2.,  0.],
       [-1.,  1.,  2.],
       [ 0., -1.,  1.],
       [ 0.,  0., -1.]])

In [27]:
# check whether we can obtain the same answer

print("the convolution of a and b computed by using Toeplitz matrix")
# @ means taking inner product 
conv_toeplitz = toeplitz(b, len(a)) @ a
print(conv_toeplitz)

print("\n")
print("the convolution of a and b")
conv

the convolution of a and b computed by using Toeplitz matrix
[ 2.  1. -3. -1.  1.]


the convolution of a and b


array([ 2,  1, -3, -1,  1])